name: Auto-update videos.json

on:
  pull_request:
    paths:
      - 'videos/**'

jobs:
  update-videos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm init -y

      - name: Run appendVideo script
        run: node scripts/appendVideo.js

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add videos.json
          git commit -m "Auto-update videos.json" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
